x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
fm <- lm(y ~ x)
summary(fm)
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
detach()
getwd()
load("acs2017_ny_data.RData")

acs2017_ny[1:10,1:7]
attach(acs2017_ny)
summary(acs2017_ny)
print(NN_obs <- length(AGE))
summary(AGE[female == 1])
summary(AGE[!female])
mean(AGE[female == 1])
sd(AGE[female == 1])
mean(AGE[!female])
sd(AGE[!female])
hist(AGE[(AGE > 90)])
mean(AGE[ (female == 1) & (AGE<90) ]) 
str(as.numeric(PUMA))
mean(PUMA)
PUMA <- as.factor(PUMA)
female <- as.factor(female)
print(levels(female)
      levels(female) <- c("male","female")      
      educ_indx <- factor((educ_nohs + 2*educ_hs + 3*educ_somecoll + 4*educ_college + 5*educ_advdeg), levels=c(1,2,3,4,5),labels = c("No HS","HS","SmColl","Bach","Adv"))
      install.packages("tidyverse")
      install.packages("plyr")
      library(tidyverse)
      library(plyr)
      levels_n <- read.csv("PUMA_levels.csv")
      levels_orig <- levels(PUMA) 
      levels_new <- join(data.frame(levels_orig),data.frame(levels_n))
      levels(PUMA) <- levels_new$New_Level
      summary(female)
      summary(PUMA)
      summary(educ_indx)
      ddply(acs2017_ny, .(PUMA), summarize, mean = round(mean(AGE), 2), sd = round(sd(AGE), 2), n_obsv = length(PUMA))
      dat_use1 <- subset(acs2017_ny,((INCWAGE > 0) & in_NYC))
      ddply(dat_use1, .(PUMA), summarize, inc90 = quantile(INCWAGE,probs = 0.9), inc10 = quantile(INCWAGE,probs = 0.1), n_obs = length(INCWAGE))
      table(educ_indx,female)
      xtabs(~educ_indx + female)
      prop.table(table(educ_indx,female))
      mean(educ_nohs[(AGE >= 25)&(AGE <= 55)])
      mean(educ_hs[(AGE >= 25)&(AGE <= 55)])
      mean(educ_somecoll[(AGE >= 25)&(AGE <= 55)])
      mean(educ_college[(AGE >= 25)&(AGE <= 55)])
      mean(educ_advdeg[(AGE >= 25)&(AGE <= 55)])
      restrict1 <- as.logical((AGE >= 25)&(AGE <= 55))
      dat_age_primeage <- subset(acs2017_ny, restrict1)
      detach()
      attach(dat_age_primeage)
      mean(educ_nohs)
      mean(educ_hs)
      mean(educ_somecoll)
      mean(educ_college)
      mean(educ_advdeg)
      detach()
      # first change the factor back into a number
      acs2017_ny$IND_number <- as.numeric(levels(acs2017_ny$IND))[acs2017_ny$IND]
      acs2017_ny$Covid_risk <- ((acs2017_ny$IND_number > 4600) & acs2017_ny$IND_number < 6000) | ((acs2017_ny$IND_number > 8500) & (acs2017_ny$IND_number < 8700))
      # then pick certain ranges of numbers
      